# Derived from official mysql image (our base image)

# Add a database

# Add the content of the .sql file to your image
# All scripts in docker-entrypoint-initdb.d/ are automatically
# executed during container startup
